blank_issues_enabled: false
contact_links:
  - name: "📚 Read docs"
    url: https://docs.gprmax.com/en/devel/
    about: Find your solution from our documenations
  - name: "😊 gprMax support"
    url: https://groups.google.com/g/gprmax
    about: |
      Please only file issues here that you believe represent actual bugs or feature requests for the gprMax software.
      If you're having general trouble with using gprMax, please visit our help center to get support.
